import * as cdk from "aws-cdk-lib";
import { Duration, RemovalPolicy, Stack, type StackProps } from "aws-cdk-lib";
import * as iam from "aws-cdk-lib/aws-iam";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as s3deploy from "aws-cdk-lib/aws-s3-deployment";
import { Construct } from "constructs";

export interface PodcastHostingStackProps extends StackProps {
    readonly githubOwner?: string;
    readonly githubRepo?: string;
    readonly githubBranch?: string;
}

export class PodcastHostingStack extends Stack {
    public constructor(scope: Construct, id: string, props: PodcastHostingStackProps = {}) {
        super(scope, id, props);

        const githubOwner = props.githubOwner ?? "quantuminformation";
        const githubRepo = props.githubRepo ?? "aws-hosted-podcast";
        const githubBranch = props.githubBranch ?? "main";

        const bucket = new s3.Bucket(this, "PodcastBucket", {
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ACLS,
            encryption: s3.BucketEncryption.S3_MANAGED,
            enforceSSL: true,
            versioned: true,
            removalPolicy: RemovalPolicy.RETAIN,
            autoDeleteObjects: false,
            publicReadAccess: true,
        });

        const githubDeployRole = new iam.Role(this, "GithubDeployRole", {
            roleName: "aws-hosted-podcast-github-deploy",
            assumedBy: new iam.FederatedPrincipal(
                "arn:aws:iam::180971085012:oidc-provider/token.actions.githubusercontent.com",
                {
                    StringEquals: {
                        "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
                    },
                    StringLike: {
                        "token.actions.githubusercontent.com:sub": `repo:${githubOwner}/${githubRepo}:ref:refs/heads/${githubBranch}`,
                    },
                },
                "sts:AssumeRoleWithWebIdentity",
            ),
            description: "GitHub Actions role for deploying The Nikos Show podcast stack",
            maxSessionDuration: Duration.hours(1),
        });

        githubDeployRole.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName("PowerUserAccess"));
        githubDeployRole.addToPolicy(new iam.PolicyStatement({
            actions: [
                "sts:AssumeRole",
            ],
            resources: [
                `arn:aws:iam::${cdk.Aws.ACCOUNT_ID}:role/cdk-hnb659fds-*`,
            ],
        }));

        new s3deploy.BucketDeployment(this, "SeedFeed", {
            destinationBucket: bucket,
            sources: [s3deploy.Source.data("feed.xml", this.renderFeedPlaceholder())],
            retainOnDelete: false,
        });

        new cdk.CfnOutput(this, "BucketName", {
            value: bucket.bucketName,
        });

        new cdk.CfnOutput(this, "FeedUrl", {
            value: `https://${bucket.bucketRegionalDomainName}/feed.xml`,
        });

        new cdk.CfnOutput(this, "GithubDeployRoleArn", {
            value: githubDeployRole.roleArn,
        });
    }

    private renderFeedPlaceholder(): string {
        return [
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            '<rss version="2.0">',
            "  <channel>",
            "    <title>The Nikos Show</title>",
            "    <description>Placeholder feed generated by CDK. Replace this with the migrated RSS feed.</description>",
            "    <link>https://example.com</link>",
            "  </channel>",
            "</rss>",
            "",
        ].join("\n");
    }
}
